name: Loop
on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Feed"]
    types: [completed]

jobs:
  restart:
    runs-on: ubuntu-latest
    steps:
      - name: Check remaining
        run: |
          REMAINING=$(curl -s -H "x-api-key: ${{ secrets.API_KEY }}" ${{ secrets.API_BASE }}/fetch-remaining | grep -o '"remaining":[0-9]*' | grep -o '[0-9]*')
          echo "REMAINING=$REMAINING" >> $GITHUB_ENV
      - name: Trigger next run
        if: env.REMAINING > 0
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: feed.yml
          token: ${{ secrets.PAT_TOKEN }}
